"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let places = ['Italy', 'Germany', 'Australia', 'England', 'Thailand'];
console.log('original ' + places);
console.log('copy ' + [...places].sort());
console.log('original ' + places);
console.log('copy ' + [...places].sort().reverse());
console.log('original ' + places);
console.log('original ' + places.reverse());
console.log('original ' + places.reverse());
console.log('original ' + places.sort());
console.log('original ' + [...places].sort().reverse());
